### ISSUE TITLE
events.js:85 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by tabirkeland** [mcasimir/generator-mobileangularui#8]
No idea whats happening here.....

[05:35:43] Using gulpfile ~/git/newApp/gulpfile.js
[05:35:43] Starting 'build'...
[05:35:43] Starting 'clean'...
[05:35:43] Finished 'clean' after 28 ms
[05:35:43] Starting 'html'...
[05:35:43] Finished 'html' after 3.76 ms
[05:35:43] Starting 'fonts'...
[05:35:43] Starting 'images'...
[05:35:43] Starting 'less'...
[05:35:43] Finished 'less' after 6.14 ms
[05:35:43] Starting 'js'...
[05:35:43] Finished 'js' after 18 ms
[05:35:43] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[05:35:43] Finished 'images' after 39 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new Parser (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/less/lib/less/parser.js:333:27)
    at Object.less.render (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/less/lib/less/index.js:18:22)
    at Transform._transform (/home/taylor/git/newApp/node_modules/gulp-less/index.js:38:10)
    at Transform._read (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/taylor/git/newApp/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/taylor/git/newApp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/taylor/git/newApp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

**Comment by pengyver** [comment]
Same error, i can build if i downgrade font-awesome to 4.2.0 version.

**Comment by Schoonmoeder** [comment]
i can confirm that for me running the next commands fixed it (in for app folder)
bower uninstall font-awesome
and
bower install font-awesome#4.2.0

choise option 1 when it ask if you want to install 4.3.x or 4.2.0 of awesome

**Comment by Hedde** [comment]
same error, same fix

**Comment by fgarci03** [comment]
same error, same fix

**Comment by eladh** [comment]
same error, same fix

**Comment by RemcovandenBerg** [comment]
Issue is fixed.

**Comment by adairborba** [comment]
same error, same fix

**Comment by jorgeramos** [comment]
yup... this worked for me as well.. thanks!

**Comment by joniturmendi** [comment]
same error, same fix
