### ISSUE TITLE
Problem with yeoman generator

### ISSUE THREAD

**Issue by Shantydroid** [mcasimir/generator-mobileangularui#9]
I have an error creating the app, instantiating "yo mobileangularui"

module.js:338

throw err;

^

Error: Cannot find module 'unicode/category/So'

at Function.Module._resolveFilename (module.js:336:15)

at Function.Module._load (module.js:278:25)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at symbols (C:\Users\maganas\AppData\Roaming\npm\node_modules\generator-mobi

leangularui\node_modules\slug\slug.js:6:16)

at C:\Users\maganas\AppData\Roaming\npm\node_modules\generator-mobileangular

ui\node_modules\slug\slug.js:123:5

at Object.<anonymous> (C:\Users\maganas\AppData\Roaming\npm\node_modules\gen

erator-mobileangularui\node_modules\slug\slug.js:130:2)

at Module._compile (module.js:460:26)

at Object.Module._extensions..js (module.js:478:10)

at Module.load (module.js:355:32)

**Comment by RemcovandenBerg** [comment]
Looks like a `npm install` is needed first. Don't think there is a problem with our package anymore. Re-open if the problem is still there. thanks.
